import { Router } from 'express';
const router = Router();
import authRouter from './auth.routes.js';
import campgaignRouter from './campaign.route.js';
import donationRouter from './donation.routes.js';
import categoryRouter from './category.route.js';
router.use('/auth', authRouter);
router.use('/campaign', campgaignRouter);
router.use('/donation', donationRouter);
router.use('/category', categoryRouter);
export default router;
